#%RAML 1.0

title: Acquisition Audit events API
baseUri: https://github.com/folio-org/mod-audit
version: v1

documentation:
  - title: Acquisition Audit events API
    content: API for retrieving events for acquisition changes

types:
  errors: !include raml-util/schemas/errors.schema
  order-line-audit-event: !include order_line_audit_event.json
  order-audit-event: !include order_audit_event.json
  order-audit-event-collection: !include order_audit_event_collection.json
  order-line-audit-event-collection: !include order_line_audit_event_collection.json
  piece-audit-event: !include piece_audit_event.json
  piece-audit-event-collection: !include piece_audit_event_collection.json
  invoice-audit-event: !include invoice_audit_event.json
  invoice-audit-event-collection: !include invoice_audit_event_collection.json
  invoice-line-audit-event-collection: !include invoice_line_audit_event_collection.json
  organization-audit-event: !include organization_audit_event.json
  organization-audit-event-collection: !include organization_audit_event_collection.json

traits:
  searchable: !include raml-util/traits/searchable.raml
  pageable: !include raml-util/traits/pageable.raml
  validate: !include raml-util/traits/validation.raml

/audit-data/acquisition:
  /order/{id}:
    get:
      description: Get list of order events by order_id
      is: [
        pageable,
        validate
      ]
      queryParameters:
        sortBy:
          description: "sorting by field: actionDate"
          type: string
          default: action_date
        sortOrder:
          description: "sort order: asc or desc"
          enum: [asc, desc]
          type: string
          default: desc
        limit:
          default: 2147483647
        offset:
          default: 0
      responses:
        200:
          body:
            application/json:
              type: order-audit-event-collection
        500:
          description: "Internal server error"
          body:
            application/json:
              type: errors
              example:
                strict: false
                value: !include raml-util/examples/errors.sample

  /order-line/{id}:
    get:
      description: Get list of order_line events by order_line_id
      is: [
          pageable,
          validate
      ]
      queryParameters:
        sortBy:
          description: "sorting by field: actionDate"
          type: string
          default: action_date
        sortOrder:
          description: "sort order: asc or desc"
          enum: [asc, desc]
          type: string
          default: desc
        limit:
          default: 2147483647
        offset:
          default: 0
      responses:
        200:
          body:
            application/json:
              type: order-line-audit-event-collection
        500:
          description: "Internal server error"
          body:
            application/json:
              type: errors

  /piece/{id}:
    get:
      description: Get list of piece events by piece_id
      is: [
        pageable,
        validate
      ]
      queryParameters:
        sortBy:
          description: "sorting by field: actionDate"
          type: string
          default: action_date
        sortOrder:
          description: "sort order: asc or desc"
          enum: [asc, desc]
          type: string
          default: desc
        limit:
          default: 2147483647
        offset:
          default: 0
      responses:
        200:
          body:
            application/json:
              type: piece-audit-event-collection
        500:
          description: "Internal server error"
          body:
            application/json:
              type: errors
              example:
                strict: false
                value: !include raml-util/examples/errors.sample
  /piece/{id}/status-change-history:
    get:
      description: Get list of piece events which have unique status changes by piece_id
      is: [
        pageable,
        validate
      ]
      queryParameters:
        sortBy:
          description: "sorting by field: actionDate"
          type: string
          default: action_date
        sortOrder:
          description: "sort order: asc or desc"
          enum: [asc, desc]
          type: string
          default: desc
        limit:
          default: 2147483647
        offset:
          default: 0
      responses:
        200:
          body:
            application/json:
              type: piece-audit-event-collection
        500:
          description: "Internal server error"
          body:
            application/json:
              type: errors
              example:
                strict: false
                value: !include raml-util/examples/errors.sample

  /invoice/{id}:
    get:
      description: Get list of invoice events by invoice_id
      is: [
        pageable,
        validate
      ]
      queryParameters:
        sortBy:
          description: "sorting by field: actionDate"
          type: string
          default: action_date
        sortOrder:
          description: "sort order: asc or desc"
          enum: [asc, desc]
          type: string
          default: desc
        limit:
          default: 2147483647
        offset:
          default: 0
      responses:
        200:
          body:
            application/json:
              type: invoice-audit-event-collection
        500:
          description: "Internal server error"
          body:
            application/json:
              type: errors
              example:
                strict: false
                value: !include raml-util/examples/errors.sample

  /invoice-line/{id}:
    get:
      description: Get list of invoice_line events by invoice_line_id
      is: [
          pageable,
          validate
      ]
      queryParameters:
        sortBy:
          description: "sorting by field: actionDate"
          type: string
          default: action_date
        sortOrder:
          description: "sort order: asc or desc"
          enum: [asc, desc]
          type: string
          default: desc
        limit:
          default: 2147483647
        offset:
          default: 0
      responses:
        200:
          body:
            application/json:
              type: invoice-line-audit-event-collection
        500:
          description: "Internal server error"
          body:
            application/json:
              type: errors

  /organization/{id}:
    get:
      description: Get list of organization events by organization_id
      is: [
        pageable,
        validate
      ]
      queryParameters:
        sortBy:
          description: "sorting by field: actionDate"
          type: string
          default: action_date
        sortOrder:
          description: "sort order: asc or desc"
          enum: [asc, desc]
          type: string
          default: desc
        limit:
          default: 2147483647
        offset:
          default: 0
      responses:
        200:
          body:
            application/json:
              type: organization-audit-event-collection
        500:
          description: "Internal server error"
          body:
            application/json:
              type: errors
              example:
                strict: false
                value: !include raml-util/examples/errors.sample
