#%RAML 1.0

title: Acquisition Audit events API
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Acquisition Audit events API
    content: API for retrieving events for acquisition changes

types:
  order-line-audit-event: !include schemas/order_line_audit_event.json
  order-audit-event: !include schemas/order_audit_event.json
