#%RAML 1.0

title: Acquisition Audit events API
baseUri: https://github.com/folio-org/mod-audit
version: v1

documentation:
  - title: Acquisition Audit events API
    content: API for retrieving events for acquisition changes


types:
  order-line-audit-event: !include order_line_audit_event.json
  order-audit-event-dto: !include order_audit_event_dto.json
  order-audit-event: !include order_audit_event.json

traits:
  searchable: !include raml-util/traits/searchable.raml

/audit-data/acquisition:
  /order/{id}:
    get:
      description: Get JobExecution by id
      responses:
        200:
          body:
            application/json:
              type: order-audit-event-dto


/audit-data/acquisition/order-line/{id}:

