#%RAML 1.0

title: Cleanup Audit API
baseUri: https://github.com/folio-org/mod-audit
version: v1

documentation:
  - title: mod-audit API
    content: API for audit related data cleanup

types:
  errors: !include raml-util/schemas/errors.schema

/audit-data/cleanup:
  /timer:
    post:
      description: Cleanup audit data (timer event)
      responses:
        204:
          description: "Cleanup ok"
        500:
          description: "Internal server error"
          body:
            application/json:
              type: errors
              example:
                strict: false
                value: !include raml-util/examples/errors.sample
