#%RAML 1.0

title: Inventory Audit API
baseUri: https://github.com/folio-org/mod-audit
version: v1

documentation:
  - title: mod-audit API
    content: API for retrieving events for inventory changes

types:
  errors: !include raml-util/schemas/errors.schema
  inventory-audit-collection: !include schemas/inventory/inventory_audit_collection.json
traits:
  validate: !include raml-util/traits/validation.raml
  seek: !include traits/seek-by-date.raml

/audit-data/inventory:
  /instance/{entityId}:
    get:
      description: Get list of instance events
      is: [
        validate,
        seek
      ]
      responses:
        200:
          body:
            application/json:
              type: inventory-audit-collection
        500:
          description: "Internal server error"
          body:
            application/json:
              type: errors
              example:
                strict: false
                value: !include raml-util/examples/errors.sample
  /holdings/{entityId}:
    get:
      description: Get list of holdings events
      is: [
        validate,
        seek
      ]
      responses:
        200:
          body:
            application/json:
              type: inventory-audit-collection
        500:
          description: "Internal server error"
          body:
            application/json:
              type: errors
              example:
                strict: false
                value: !include raml-util/examples/errors.sample
  /item/{entityId}:
    get:
      description: Get list of item events
      is: [
        validate,
        seek
      ]
      responses:
        200:
          body:
            application/json:
              type: inventory-audit-collection
        500:
          description: "Internal server error"
          body:
            application/json:
              type: errors
              example:
                strict: false
                value: !include raml-util/examples/errors.sample

