#%RAML 1.0

title: Marc Audit API
baseUri: https://github.com/folio-org/mod-audit
version: v1

documentation:
  - title: mod-audit API
    content: API for retrieving events for marc record changes

types:
  errors: !include raml-util/schemas/errors.schema
  marc_audit_collection: !include schemas/marc/marc_audit_collection.json
traits:
  validate: !include raml-util/traits/validation.raml
  seek: !include traits/seek-by-date.raml

/audit-data/marc:
  /bib/{entityId}:
    get:
      description: Get list of marc record events
      is: [
        validate,
        seek
      ]
      responses:
        200:
          body:
            application/json:
              type: marc_audit_collection
        500:
          description: "Internal server error"
          body:
            application/json:
              type: errors
              example:
                strict: false
                value: !include raml-util/examples/errors.sample
  /authority/{entityId}:
    get:
      description: Get list of authority record events
      is: [
        validate,
        seek
      ]
      responses:
        200:
          body:
            application/json:
              type: marc_audit_collection
        500:
          description: "Internal server error"
          body:
            application/json:
              type: errors
              example:
                strict: false
                value: !include raml-util/examples/errors.sample
